name: Build and Release Mod

on:
  create:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build project
        run: ./gradlew build

      - name: Extract properties from gradle.properties
        id: properties
        run: |
          modId=$(grep 'modId' gradle.properties | cut -d'=' -f2)
          minecraftFirstSnapshotVersion=$(grep 'minecraftFirstSnapshotVersion' gradle.properties | cut -d'=' -f2)
          minecraftReleaseVersion=$(grep 'minecraftReleaseVersion' gradle.properties | cut -d'=' -f2)
          fabricSupportedLoaders=$(grep 'fabricSupportedLoaders' gradle.properties | cut -d'=' -f2)
          # Преобразование списка загрузчиков в формат для Modrinth
          loaders=$(echo $fabricSupportedLoaders | sed 's/, */,/g' | tr ',' '\n')
          echo "MOD_ID=$modId" >> $GITHUB_ENV
          echo "MINECRAFT_VERSIONS=Minecraft: $minecraftFirstSnapshotVersion-$minecraftReleaseVersion" >> $GITHUB_ENV
          echo "LOADERS=Loaders: $fabricSupportedLoaders" >> $GITHUB_ENV
          echo "MINECRAFT_FIRST_SNAPSHOT_VERSION=$minecraftFirstSnapshotVersion" >> $GITHUB_ENV
          echo "MINECRAFT_RELEASE_VERSION=$minecraftReleaseVersion" >> $GITHUB_ENV
          echo "LOADERS_FOR_MODRINTH=$loaders" >> $GITHUB_ENV

      - name: Get version changelog
        id: changelog
        run: |
          VERSION=$(basename ${{ github.ref }})
          CHANGELOG=$(sed -n "/^## $VERSION$/,/^## [0-9]/p" CHANGELOG.md | sed '$d' | tail -n +2)
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        shell: bash

      - name: Combine release notes
        id: combine
        run: |
          echo "${{ env.MINECRAFT_VERSIONS }}" > combined_changelog.txt
          echo "${{ env.LOADERS }}" >> combined_changelog.txt
          echo "" >> combined_changelog.txt
          echo "## Changes" >> combined_changelog.txt
          echo "" >> combined_changelog.txt
          echo "${{ env.CHANGELOG }}" >> combined_changelog.txt
          cat combined_changelog.txt
          echo "FINAL_CHANGELOG<<EOF" >> $GITHUB_ENV
          cat combined_changelog.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Foggy Pale Garden ${{ github.ref_name }}"
          files: build/libs/*.jar
          body: ${{ env.FINAL_CHANGELOG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Modrinth
        uses: modrinth/modrinth-publish-action@v1
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project-id: ${{ env.MOD_ID }}
          version-name: ${{ github.ref_name }}
          version-number: ${{ github.ref_name }}
          changelog: ${{ env.CHANGELOG }}
          game-versions: |
            ${{ env.MINECRAFT_FIRST_SNAPSHOT_VERSION }}
            ${{ env.MINECRAFT_RELEASE_VERSION }}
          loaders: ${{ env.LOADERS_FOR_MODRINTH }}
          release-channel: "release"
          primary-file: "build/libs/${{ env.MOD_ID }}-${{ env.MINECRAFT_RELEASE_VERSION }}-${{ github.ref_name }}.jar"
          additional-files: "build/libs/${{ env.MOD_ID }}-${{ env.MINECRAFT_RELEASE_VERSION }}-${{ github.ref_name }}-sources.jar"

#      - name: Publish to CurseForge
#        uses: CurseForgePublishing/release-action@v1
#        with:
#          api-key: ${{ secrets.CURSEFORGE_API_KEY }}
#          game-id: "432"
#          project-id: "your-curseforge-project-id"
#          file: build/libs/*.jar
#          changelog: ${{ env.FINAL_CHANGELOG }}
#          version: ${{ github.ref_name }}
#          release-type: release